//! Stable maintained witness identifiers shared by focused probes and contract targets.

pub(super) const PROGRESSION_MAINTAINED_ANCHOR_SEED: u64 = 0xD33F_C01D_5052;
pub(super) const PROGRESSION_REFINEMENT_COVERAGE_SEED: u64 = 3;
pub(super) const PROGRESSION_SURFACE_RESOLVED_COVERAGE_SEED: u64 = 4;
pub(super) const LIBERATION_MANUAL_FALLBACK_COVERAGE_SEED: u64 = 0x4C49_4245_4641_4C4C;
pub(super) const SURVIVAL_BALANCED_PRESERVATION_COVERAGE_SEED: u64 = 2;
pub(super) const SURVIVAL_BALANCED_PRESERVATION_BEHAVIOR_SEED: u64 = 0xAB2C_977A_0B20_C7A3;
pub(super) const SURVIVAL_STRONG_PRESERVATION_COVERAGE_SEED: u64 = 17;
pub(super) const SURVIVAL_STRONG_PRESERVATION_BEHAVIOR_SEED: u64 = 0x0274_20B1_9FB8_38F7;
pub(super) const SURVIVAL_DECLINE_COVERAGE_SEED: u64 = 0x043C_561D_398D_32BA;
pub(super) const SURVIVAL_CONTINUATION_COVERAGE_SEED: u64 = 10;
pub(super) const FIELDWORK_ADAPTIVE_RETOOL_COVERAGE_SEED: u64 = 11;
pub(super) const FIELDWORK_PROJECT_HORIZON_COVERAGE_SEED: u64 = 7;
pub(super) const ORE_FINITE_ENERGY_COVERAGE_SEED: u64 = 2;
pub(super) const FOUNDRY_BOOTSTRAP_RECOVERY_COVERAGE_SEED: u64 = 0x0000_0000_0000_0041;
pub(super) const FOUNDRY_MAINTAINED_ANCHOR_SEED: u64 = 0xD33F_C01D_F001;
pub(super) const FOUNDRY_THERMAL_RECOVERY_COVERAGE_SEED: u64 = 2;
