//! Builds immutable built-in registries and exports stable content identities.

mod capabilities;
mod crafted_parts;
mod crafting;
mod energy;
mod equipment;
mod fluid;
#[cfg(feature = "test-gameplay")]
#[doc(hidden)]
pub mod gameplay_fixture;
mod labor;
mod materials;
mod mining;
mod ore_processing;
mod processes;
mod shaders;
mod storage;
mod structural;
mod survival;
#[cfg(test)]
mod test_support;
mod textures;
mod thermal;

use crate::core::quantity::Acceleration;
use crate::core::time::CalendarDefinition;
use crate::registry::{
    CoreDefinitions, Registries, RegistryDomains, RegistryPresentation, RegistrySchemaVersion,
};
pub use fluid::FLUID_WATER;
pub use labor::{
    MANUAL_POWER_FOOT_TREADLE, MANUAL_POWER_HAND_CRANK, MANUAL_POWER_TREADLE_DYNAMO,
    MANUAL_POWER_WALKING_WHEEL, PROSPECTING_DETAILED_FIELD_SURVEY, PROSPECTING_FIELD_INSPECTION,
    PROSPECTING_INDEXED_CHANNEL_SURVEY, PROSPECTING_LOCAL_TRANSECT,
    PROSPECTING_REGIONAL_RECONNAISSANCE,
};
pub use mining::MINING_METHOD_HAND_PICK;
#[cfg(test)]
pub(crate) use test_support::{
    STANDARD_TEST_HEATER, STANDARD_TEST_HEATING_ENERGY, STANDARD_TEST_SCREEN,
    STANDARD_TEST_SCREENING_ENERGY, make_test_registries_with_casting,
    make_test_registries_with_comminution, make_test_registries_with_energy_store,
    make_test_registries_with_energy_store_and_survival, make_test_registries_with_equipment,
    make_test_registries_with_fluids, make_test_registries_with_melting,
    make_test_registries_with_screening, make_test_registries_with_sensible_heating,
    make_test_registries_with_standard_screening,
    make_test_registries_with_standard_sensible_heating,
};
#[cfg(test)]
use test_support::{
    empty_energy_registry, empty_equipment_registry, empty_shader_registry, empty_texture_registry,
    empty_thermal_registry,
};

pub use energy::{
    ENERGY_COPPER_BANDED_STONE_FLYWHEEL_DRIVE, ENERGY_COPPER_PLATE_ELECTRICAL_BUFFER,
    ENERGY_ELECTRICAL_BUFFER, ENERGY_MECHANICAL_LARGE_DRIVE, ENERGY_MECHANICAL_SMALL_DRIVE,
    ENERGY_PAIRED_STONE_FLYWHEEL_DRIVE, ENERGY_STONE_FLYWHEEL_DRIVE, ENERGY_STONE_THERMAL_SINK,
    ENERGY_THERMAL_SINK, ENERGY_TIMBER_FLYWHEEL_DRIVE, ENERGY_TIMBER_FRAME_FLYWHEEL_BANK,
};
pub use equipment::{
    EQUIPMENT_CASTING_MOLD, EQUIPMENT_COPPER_PLATE_SIZING_SCREEN,
    EQUIPMENT_COPPER_REINFORCED_GEOLOGICAL_HAMMER, EQUIPMENT_COPPER_REINFORCED_HAND_CRANK,
    EQUIPMENT_COPPER_REINFORCED_PICK, EQUIPMENT_COPPER_REINFORCED_STONE_CRUSHER,
    EQUIPMENT_COPPER_REINFORCED_STONE_QUARRY_PICK, EQUIPMENT_COPPER_REINFORCED_STONE_ROTARY_QUERN,
    EQUIPMENT_COPPER_REINFORCED_STONE_SEPARATOR, EQUIPMENT_COPPER_REINFORCED_WOODWORKING_ADZE,
    EQUIPMENT_DRY_SCREEN, EQUIPMENT_ELECTRIC_FURNACE, EQUIPMENT_GRAVITY_SEPARATOR,
    EQUIPMENT_GRINDING_MILL, EQUIPMENT_JAW_CRUSHER, EQUIPMENT_STONE_ARC_CRUCIBLE_FURNACE,
    EQUIPMENT_STONE_COBBING_HAMMER, EQUIPMENT_STONE_CRUSHER, EQUIPMENT_STONE_FLYWHEEL_PUMP_DRILL,
    EQUIPMENT_STONE_GEOLOGICAL_HAMMER, EQUIPMENT_STONE_HAND_CRANK, EQUIPMENT_STONE_INGOT_MOLD,
    EQUIPMENT_STONE_PICK, EQUIPMENT_STONE_QUARRY_PICK, EQUIPMENT_STONE_ROTARY_QUERN,
    EQUIPMENT_STONE_SEPARATOR, EQUIPMENT_STONE_WOODWORKING_ADZE, EQUIPMENT_TIMBER_DRESSING_BENCH,
    EQUIPMENT_TIMBER_FLYWHEEL_GRINDING_BENCH, EQUIPMENT_TIMBER_FLYWHEEL_LATHE,
    EQUIPMENT_TIMBER_FRAME_COMMINUTION_MILL, EQUIPMENT_TIMBER_FRAME_SAW_BENCH,
    EQUIPMENT_TIMBER_HELVE_HAMMER, EQUIPMENT_TIMBER_ORE_DRESSING_TABLE,
    EQUIPMENT_TIMBER_RIDDLE_SIZING_SCREEN, EQUIPMENT_TIMBER_SASH_SAWMILL,
    EQUIPMENT_TIMBER_SPINDLE_DRILL, EQUIPMENT_TIMBER_SPRING_POLE_LATHE,
    EQUIPMENT_TIMBER_TREADLE_DRIVE, EQUIPMENT_TIMBER_TREADLE_DYNAMO,
    EQUIPMENT_TIMBER_TREADLE_GRINDSTONE, EQUIPMENT_TIMBER_TREADLE_HAMMER,
    EQUIPMENT_TIMBER_WALKING_WHEEL_DRIVE,
};
pub use materials::{
    FORM_BOARD, FORM_BULK_CRATE_BODY, FORM_CHEST_BODY, FORM_CHIP, FORM_CONCENTRATE, FORM_CRUSHED,
    FORM_DOUBLE_WALL_CHEST_BODY, FORM_DRILL_BIT, FORM_EXHAUSTED_TAILINGS, FORM_FLYWHEEL, FORM_FOOD,
    FORM_GRINDSTONE_WHEEL, FORM_HANDLE, FORM_INGOT, FORM_INSULATED_PANTRY_BODY, FORM_LOG,
    FORM_LUMP, FORM_MOLTEN, FORM_NATIVE_METAL, FORM_ORE, FORM_REINFORCEMENT, FORM_ROUGH_BOX_BODY,
    FORM_SAW_BLADE, FORM_SCRAP, FORM_SCREEN_PLATE, FORM_STONE_CROCK_BODY, FORM_TAILINGS,
    FORM_TIMBER_RIDDLE_PANEL, FORM_TOOL, MATERIAL_BERRIES, MATERIAL_CLAY, MATERIAL_COPPER,
    MATERIAL_GRAIN, MATERIAL_LEGUMES, MATERIAL_MEAT, MATERIAL_SLAG, MATERIAL_STONE, MATERIAL_WATER,
    MATERIAL_WOOD,
};
pub use processes::{
    PROCESS_ASSEMBLE_BULK_TIMBER_CRATE, PROCESS_ASSEMBLE_DOUBLE_WALL_TIMBER_CHEST,
    PROCESS_ASSEMBLE_INSULATED_TIMBER_PANTRY, PROCESS_ASSEMBLE_ROUGH_TIMBER_FIELD_BOX,
    PROCESS_ASSEMBLE_TIMBER_CHEST, PROCESS_CAST_PURE_COPPER,
    PROCESS_CLEAN_NATIVE_COPPER_CONCENTRATE, PROCESS_COLD_WORK_COPPER_INGOT_REINFORCEMENT,
    PROCESS_COLD_WORK_COPPER_REINFORCEMENT, PROCESS_COLD_WORK_COPPER_SAW_BLADE,
    PROCESS_COLD_WORK_COPPER_SCRAP_REINFORCEMENT, PROCESS_CONCENTRATE_COPPER, PROCESS_CRUSH_ORE,
    PROCESS_DRESS_STONE_CHIP_DRILL_BIT, PROCESS_FINE_GRIND_SCREEN_OVERSIZE,
    PROCESS_GRIND_CRUSHED_ORE, PROCESS_GRIND_STONE_SCRAP_DRILL_BIT, PROCESS_GRIND_STONE_SCRAP_TOOL,
    PROCESS_HAND_BREAK_ORE, PROCESS_HAND_SORT_NATIVE_COPPER, PROCESS_HEAT_MATERIAL_BATCH,
    PROCESS_KNAP_STONE_DRILL_BIT, PROCESS_KNAP_STONE_TOOL, PROCESS_MELT_PURE_COPPER,
    PROCESS_PIERCE_COPPER_SCREEN_PLATE, PROCESS_POWER_DRILL_COPPER_SCREEN_PLATE,
    PROCESS_POWER_GRIND_STONE_SCRAP_DRILL_BIT, PROCESS_POWER_GRIND_STONE_SCRAP_TOOL,
    PROCESS_POWER_HAMMER_COPPER_REINFORCEMENT, PROCESS_POWER_HAMMER_COPPER_SAW_BLADE,
    PROCESS_POWER_HAMMER_COPPER_SCRAP_REINFORCEMENT, PROCESS_POWER_SAW_WOOD_BOARDS,
    PROCESS_POWER_TURN_TIMBER_FLYWHEEL, PROCESS_POWER_TURN_WOOD_HANDLE,
    PROCESS_RECOVER_WOOD_SCRAP_BOARDS, PROCESS_REGRIND_COPPER_TAILINGS,
    PROCESS_REKNAP_STONE_SCRAP_TOOL, PROCESS_REWORK_WOOD_SCRAP_HANDLE,
    PROCESS_SALVAGE_BULK_TIMBER_CRATE_BODY, PROCESS_SALVAGE_DOUBLE_WALL_TIMBER_CHEST_BODY,
    PROCESS_SALVAGE_INSULATED_TIMBER_PANTRY_BODY, PROCESS_SALVAGE_ROUGH_TIMBER_FIELD_BOX_BODY,
    PROCESS_SALVAGE_STONE_PROVISIONS_CROCK_BODY, PROCESS_SALVAGE_TIMBER_CHEST_BODY,
    PROCESS_SAW_WOOD_BOARDS, PROCESS_SCAVENGE_COPPER_TAILINGS, PROCESS_SCREEN_CRUSHED_ORE,
    PROCESS_SEPARATE_NATIVE_COPPER, PROCESS_SHAPE_STONE_FLYWHEEL,
    PROCESS_SHAPE_STONE_GRINDSTONE_WHEEL, PROCESS_SHAPE_STONE_PROVISIONS_CROCK,
    PROCESS_SHAPE_TIMBER_FLYWHEEL, PROCESS_SHAPE_TIMBER_RIDDLE_PANEL, PROCESS_SHAPE_WOOD_BOARDS,
    PROCESS_SHAPE_WOOD_HANDLE,
};
pub use shaders::{
    SHADER_BLOOM, SHADER_LIGHT_CULL, SHADER_POST_PROCESS, SHADER_SHADOW, SHADER_SHADOW_CUTOUT,
    SHADER_SKY, SHADER_SMOKE, SHADER_SURFACE, SHADER_WATER,
};
pub use storage::{
    STORAGE_BULK_TIMBER_PROVISIONS_CRATE, STORAGE_CARVED_STONE_PROVISIONS_CROCK,
    STORAGE_DOUBLE_WALL_TIMBER_PROVISIONS_CHEST, STORAGE_INSULATED_TIMBER_PANTRY,
    STORAGE_ROUGH_TIMBER_FIELD_BOX, STORAGE_TIMBER_PROVISIONS_CHEST,
};
pub use structural::{STRUCTURAL_PROFILE_AXIAL_COMPRESSION, STRUCTURAL_PROFILE_AXIAL_TENSION};
pub use textures::{
    BLOCK_COPPER, BLOCK_COPPER_ORE, BLOCK_TIMBER, OBJECT_BULK_TIMBER_CRATE_BODY,
    OBJECT_CASTING_MOLD, OBJECT_COPPER_INGOT, OBJECT_COPPER_ORE, OBJECT_COPPER_PLATE_SIZING_SCREEN,
    OBJECT_COPPER_REINFORCED_GEOLOGICAL_HAMMER, OBJECT_COPPER_REINFORCED_HAND_CRANK,
    OBJECT_COPPER_REINFORCED_PICK, OBJECT_COPPER_REINFORCED_STONE_CRUSHER,
    OBJECT_COPPER_REINFORCED_STONE_QUARRY_PICK, OBJECT_COPPER_REINFORCED_STONE_ROTARY_QUERN,
    OBJECT_COPPER_REINFORCED_STONE_SEPARATOR, OBJECT_COPPER_REINFORCED_WOODWORKING_ADZE,
    OBJECT_COPPER_REINFORCEMENT, OBJECT_COPPER_SAW_BLADE, OBJECT_COPPER_SCRAP,
    OBJECT_COPPER_SCREEN_PLATE, OBJECT_CRUSHED_ORE, OBJECT_DOUBLE_WALL_TIMBER_CHEST_BODY,
    OBJECT_DRY_SCREEN, OBJECT_ELECTRIC_FURNACE, OBJECT_GRAVITY_SEPARATOR, OBJECT_GRINDING_MILL,
    OBJECT_INSULATED_TIMBER_PANTRY_BODY, OBJECT_JAW_CRUSHER, OBJECT_LOG, OBJECT_MOLTEN_COPPER,
    OBJECT_NATIVE_COPPER, OBJECT_ROUGH_TIMBER_FIELD_BOX_BODY, OBJECT_STONE_CHIP,
    OBJECT_STONE_COBBING_HAMMER, OBJECT_STONE_CRUSHER, OBJECT_STONE_DRILL_BIT,
    OBJECT_STONE_FLYWHEEL, OBJECT_STONE_FLYWHEEL_PUMP_DRILL, OBJECT_STONE_GEOLOGICAL_HAMMER,
    OBJECT_STONE_GRINDSTONE_WHEEL, OBJECT_STONE_HAND_CRANK, OBJECT_STONE_LUMP, OBJECT_STONE_PICK,
    OBJECT_STONE_PROVISIONS_CROCK_BODY, OBJECT_STONE_QUARRY_PICK, OBJECT_STONE_ROTARY_QUERN,
    OBJECT_STONE_SEPARATOR, OBJECT_STONE_TOOL, OBJECT_STONE_WOODWORKING_ADZE, OBJECT_TAILINGS,
    OBJECT_TIMBER_CHEST_BODY, OBJECT_TIMBER_DRESSING_BENCH, OBJECT_TIMBER_FLYWHEEL,
    OBJECT_TIMBER_FLYWHEEL_GRINDING_BENCH, OBJECT_TIMBER_FLYWHEEL_LATHE,
    OBJECT_TIMBER_FRAME_COMMINUTION_MILL, OBJECT_TIMBER_FRAME_SAW_BENCH,
    OBJECT_TIMBER_HELVE_HAMMER, OBJECT_TIMBER_ORE_DRESSING_TABLE, OBJECT_TIMBER_RIDDLE_PANEL,
    OBJECT_TIMBER_RIDDLE_SIZING_SCREEN, OBJECT_TIMBER_SASH_SAWMILL, OBJECT_TIMBER_SPINDLE_DRILL,
    OBJECT_TIMBER_SPRING_POLE_LATHE, OBJECT_TIMBER_TREADLE_DRIVE, OBJECT_TIMBER_TREADLE_GRINDSTONE,
    OBJECT_TIMBER_TREADLE_HAMMER, OBJECT_TIMBER_WALKING_WHEEL_DRIVE, OBJECT_WOOD_BOARD,
    OBJECT_WOOD_CHIP, OBJECT_WOOD_HANDLE, TEXTURE_COPPER_HAMMERED, TEXTURE_COPPER_ORE,
    TEXTURE_CRUSHED_ORE, TEXTURE_MACHINE_PANEL, TEXTURE_MOLTEN_COPPER, TEXTURE_REFRACTORY,
    TEXTURE_SCREEN_MESH, TEXTURE_SLAG, TEXTURE_STONE, TEXTURE_WOOD_END, TEXTURE_WOOD_SIDE,
    TEXTURE_WORKING_METAL,
};

const DEFAULT_GRAVITY_MICROMETERS_PER_SECOND_SQUARED: u64 = 9_806_650;
const DEFAULT_TICKS_PER_DAY: u64 = 24_000;
const DEFAULT_PHYSICAL_SECONDS_PER_DAY: u32 = 86_400;
const DEFAULT_DAYS_PER_MONTH: u16 = 8;
const DEFAULT_MONTHS_PER_YEAR: u16 = 12;
const REGISTRY_SCHEMA_VERSION: RegistrySchemaVersion = RegistrySchemaVersion::new(113);

fn build_core_definitions() -> CoreDefinitions {
    CoreDefinitions::new(
        Acceleration::from_micrometers_per_second_squared(
            DEFAULT_GRAVITY_MICROMETERS_PER_SECOND_SQUARED,
        ),
        CalendarDefinition::new(
            DEFAULT_TICKS_PER_DAY,
            DEFAULT_PHYSICAL_SECONDS_PER_DAY,
            DEFAULT_DAYS_PER_MONTH,
            DEFAULT_MONTHS_PER_YEAR,
        ),
    )
}

/// Builds the immutable built-in registry set used by a new application instance.
#[must_use]
pub fn build_registries() -> Registries {
    Registries::new(
        REGISTRY_SCHEMA_VERSION,
        build_core_definitions(),
        RegistryDomains {
            energy: energy::build_energy_registry(),
            fluid: fluid::build_fluid_registry(),
            capabilities: capabilities::build_capability_registry(),
            crafting: crafting::build_crafting_registry(),
            labor: labor::build_labor_registry(),
            equipment: equipment::build_equipment_registry(),
            storage: storage::build_storage_registry(),
            structural: structural::build_structural_registry(),
            materials: materials::build_material_registry(),
            mining: mining::build_mining_registry(),
            ore_processing: ore_processing::build_ore_processing_registry(),
            thermal: thermal::build_thermal_registry(),
            production: processes::build_production_registry(),
            survival: survival::build_survival_registry(),
            presentation: RegistryPresentation {
                textures: textures::build_texture_registry(),
                shaders: shaders::build_shader_registry(),
            },
        },
    )
}

#[cfg(test)]
#[path = "mod_tests.rs"]
mod tests;
