//! Equipment-to-object appearance bindings for player-visible equipment identities.

use crate::content::equipment::{
    EQUIPMENT_CASTING_MOLD, EQUIPMENT_COPPER_PLATE_SIZING_SCREEN,
    EQUIPMENT_COPPER_REINFORCED_GEOLOGICAL_HAMMER, EQUIPMENT_COPPER_REINFORCED_HAND_CRANK,
    EQUIPMENT_COPPER_REINFORCED_PICK, EQUIPMENT_COPPER_REINFORCED_STONE_CRUSHER,
    EQUIPMENT_COPPER_REINFORCED_STONE_QUARRY_PICK, EQUIPMENT_COPPER_REINFORCED_STONE_ROTARY_QUERN,
    EQUIPMENT_COPPER_REINFORCED_STONE_SEPARATOR, EQUIPMENT_COPPER_REINFORCED_WOODWORKING_ADZE,
    EQUIPMENT_DRY_SCREEN, EQUIPMENT_ELECTRIC_FURNACE, EQUIPMENT_GRAVITY_SEPARATOR,
    EQUIPMENT_GRINDING_MILL, EQUIPMENT_JAW_CRUSHER, EQUIPMENT_STONE_ARC_CRUCIBLE_FURNACE,
    EQUIPMENT_STONE_COBBING_HAMMER, EQUIPMENT_STONE_CRUSHER, EQUIPMENT_STONE_FLYWHEEL_PUMP_DRILL,
    EQUIPMENT_STONE_GEOLOGICAL_HAMMER, EQUIPMENT_STONE_HAND_CRANK, EQUIPMENT_STONE_INGOT_MOLD,
    EQUIPMENT_STONE_PICK, EQUIPMENT_STONE_QUARRY_PICK, EQUIPMENT_STONE_ROTARY_QUERN,
    EQUIPMENT_STONE_SEPARATOR, EQUIPMENT_STONE_WOODWORKING_ADZE, EQUIPMENT_TIMBER_DRESSING_BENCH,
    EQUIPMENT_TIMBER_FLYWHEEL_GRINDING_BENCH, EQUIPMENT_TIMBER_FLYWHEEL_LATHE,
    EQUIPMENT_TIMBER_FRAME_COMMINUTION_MILL, EQUIPMENT_TIMBER_FRAME_SAW_BENCH,
    EQUIPMENT_TIMBER_HELVE_HAMMER, EQUIPMENT_TIMBER_ORE_DRESSING_TABLE,
    EQUIPMENT_TIMBER_RIDDLE_SIZING_SCREEN, EQUIPMENT_TIMBER_SASH_SAWMILL,
    EQUIPMENT_TIMBER_SPINDLE_DRILL, EQUIPMENT_TIMBER_SPRING_POLE_LATHE,
    EQUIPMENT_TIMBER_TREADLE_DRIVE, EQUIPMENT_TIMBER_TREADLE_DYNAMO,
    EQUIPMENT_TIMBER_TREADLE_GRINDSTONE, EQUIPMENT_TIMBER_TREADLE_HAMMER,
    EQUIPMENT_TIMBER_WALKING_WHEEL_DRIVE,
};
use crate::texture::EquipmentAppearanceBinding;

use super::super::{
    OBJECT_CASTING_MOLD, OBJECT_COPPER_PLATE_SIZING_SCREEN,
    OBJECT_COPPER_REINFORCED_GEOLOGICAL_HAMMER, OBJECT_COPPER_REINFORCED_HAND_CRANK,
    OBJECT_COPPER_REINFORCED_PICK, OBJECT_COPPER_REINFORCED_STONE_CRUSHER,
    OBJECT_COPPER_REINFORCED_STONE_QUARRY_PICK, OBJECT_COPPER_REINFORCED_STONE_ROTARY_QUERN,
    OBJECT_COPPER_REINFORCED_STONE_SEPARATOR, OBJECT_COPPER_REINFORCED_WOODWORKING_ADZE,
    OBJECT_DRY_SCREEN, OBJECT_ELECTRIC_FURNACE, OBJECT_GRAVITY_SEPARATOR, OBJECT_GRINDING_MILL,
    OBJECT_JAW_CRUSHER, OBJECT_STONE_ARC_CRUCIBLE_FURNACE, OBJECT_STONE_COBBING_HAMMER,
    OBJECT_STONE_CRUSHER, OBJECT_STONE_FLYWHEEL_PUMP_DRILL, OBJECT_STONE_GEOLOGICAL_HAMMER,
    OBJECT_STONE_HAND_CRANK, OBJECT_STONE_INGOT_MOLD, OBJECT_STONE_PICK, OBJECT_STONE_QUARRY_PICK,
    OBJECT_STONE_ROTARY_QUERN, OBJECT_STONE_SEPARATOR, OBJECT_STONE_WOODWORKING_ADZE,
    OBJECT_TIMBER_DRESSING_BENCH, OBJECT_TIMBER_FLYWHEEL_GRINDING_BENCH,
    OBJECT_TIMBER_FLYWHEEL_LATHE, OBJECT_TIMBER_FRAME_COMMINUTION_MILL,
    OBJECT_TIMBER_FRAME_SAW_BENCH, OBJECT_TIMBER_HELVE_HAMMER, OBJECT_TIMBER_ORE_DRESSING_TABLE,
    OBJECT_TIMBER_RIDDLE_SIZING_SCREEN, OBJECT_TIMBER_SASH_SAWMILL, OBJECT_TIMBER_SPINDLE_DRILL,
    OBJECT_TIMBER_SPRING_POLE_LATHE, OBJECT_TIMBER_TREADLE_DRIVE, OBJECT_TIMBER_TREADLE_DYNAMO,
    OBJECT_TIMBER_TREADLE_GRINDSTONE, OBJECT_TIMBER_TREADLE_HAMMER,
    OBJECT_TIMBER_WALKING_WHEEL_DRIVE,
};

pub(in crate::content::textures) fn build_equipment_bindings() -> Vec<EquipmentAppearanceBinding> {
    vec![
        EquipmentAppearanceBinding::new(EQUIPMENT_JAW_CRUSHER, OBJECT_JAW_CRUSHER),
        EquipmentAppearanceBinding::new(EQUIPMENT_ELECTRIC_FURNACE, OBJECT_ELECTRIC_FURNACE),
        EquipmentAppearanceBinding::new(EQUIPMENT_CASTING_MOLD, OBJECT_CASTING_MOLD),
        EquipmentAppearanceBinding::new(EQUIPMENT_DRY_SCREEN, OBJECT_DRY_SCREEN),
        EquipmentAppearanceBinding::new(EQUIPMENT_GRINDING_MILL, OBJECT_GRINDING_MILL),
        EquipmentAppearanceBinding::new(EQUIPMENT_STONE_PICK, OBJECT_STONE_PICK),
        EquipmentAppearanceBinding::new(EQUIPMENT_STONE_HAND_CRANK, OBJECT_STONE_HAND_CRANK),
        EquipmentAppearanceBinding::new(EQUIPMENT_STONE_QUARRY_PICK, OBJECT_STONE_QUARRY_PICK),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_TREADLE_DRIVE,
            OBJECT_TIMBER_TREADLE_DRIVE,
        ),
        EquipmentAppearanceBinding::new(EQUIPMENT_STONE_CRUSHER, OBJECT_STONE_CRUSHER),
        EquipmentAppearanceBinding::new(EQUIPMENT_STONE_SEPARATOR, OBJECT_STONE_SEPARATOR),
        EquipmentAppearanceBinding::new(EQUIPMENT_STONE_ROTARY_QUERN, OBJECT_STONE_ROTARY_QUERN),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_STONE_GEOLOGICAL_HAMMER,
            OBJECT_STONE_GEOLOGICAL_HAMMER,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_STONE_COBBING_HAMMER,
            OBJECT_STONE_COBBING_HAMMER,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_STONE_FLYWHEEL_PUMP_DRILL,
            OBJECT_STONE_FLYWHEEL_PUMP_DRILL,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_SPINDLE_DRILL,
            OBJECT_TIMBER_SPINDLE_DRILL,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_SPRING_POLE_LATHE,
            OBJECT_TIMBER_SPRING_POLE_LATHE,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_FLYWHEEL_LATHE,
            OBJECT_TIMBER_FLYWHEEL_LATHE,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_TREADLE_GRINDSTONE,
            OBJECT_TIMBER_TREADLE_GRINDSTONE,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_FLYWHEEL_GRINDING_BENCH,
            OBJECT_TIMBER_FLYWHEEL_GRINDING_BENCH,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_PLATE_SIZING_SCREEN,
            OBJECT_COPPER_PLATE_SIZING_SCREEN,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_RIDDLE_SIZING_SCREEN,
            OBJECT_TIMBER_RIDDLE_SIZING_SCREEN,
        ),
        EquipmentAppearanceBinding::new(EQUIPMENT_GRAVITY_SEPARATOR, OBJECT_GRAVITY_SEPARATOR),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_PICK,
            OBJECT_COPPER_REINFORCED_PICK,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_HAND_CRANK,
            OBJECT_COPPER_REINFORCED_HAND_CRANK,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_STONE_QUARRY_PICK,
            OBJECT_COPPER_REINFORCED_STONE_QUARRY_PICK,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_STONE_CRUSHER,
            OBJECT_COPPER_REINFORCED_STONE_CRUSHER,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_STONE_SEPARATOR,
            OBJECT_COPPER_REINFORCED_STONE_SEPARATOR,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_STONE_ROTARY_QUERN,
            OBJECT_COPPER_REINFORCED_STONE_ROTARY_QUERN,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_GEOLOGICAL_HAMMER,
            OBJECT_COPPER_REINFORCED_GEOLOGICAL_HAMMER,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_STONE_WOODWORKING_ADZE,
            OBJECT_STONE_WOODWORKING_ADZE,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_COPPER_REINFORCED_WOODWORKING_ADZE,
            OBJECT_COPPER_REINFORCED_WOODWORKING_ADZE,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_FRAME_SAW_BENCH,
            OBJECT_TIMBER_FRAME_SAW_BENCH,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_DRESSING_BENCH,
            OBJECT_TIMBER_DRESSING_BENCH,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_FRAME_COMMINUTION_MILL,
            OBJECT_TIMBER_FRAME_COMMINUTION_MILL,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_ORE_DRESSING_TABLE,
            OBJECT_TIMBER_ORE_DRESSING_TABLE,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_WALKING_WHEEL_DRIVE,
            OBJECT_TIMBER_WALKING_WHEEL_DRIVE,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_TREADLE_HAMMER,
            OBJECT_TIMBER_TREADLE_HAMMER,
        ),
        EquipmentAppearanceBinding::new(EQUIPMENT_TIMBER_SASH_SAWMILL, OBJECT_TIMBER_SASH_SAWMILL),
        EquipmentAppearanceBinding::new(EQUIPMENT_TIMBER_HELVE_HAMMER, OBJECT_TIMBER_HELVE_HAMMER),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_TIMBER_TREADLE_DYNAMO,
            OBJECT_TIMBER_TREADLE_DYNAMO,
        ),
        EquipmentAppearanceBinding::new(
            EQUIPMENT_STONE_ARC_CRUCIBLE_FURNACE,
            OBJECT_STONE_ARC_CRUCIBLE_FURNACE,
        ),
        EquipmentAppearanceBinding::new(EQUIPMENT_STONE_INGOT_MOLD, OBJECT_STONE_INGOT_MOLD),
    ]
}
