//! Typed failures for trusted-load validation of exclusive player work.

use crate::core::quantity::{Energy, Mass, Volume};
use crate::equipment::EquipmentId;
use crate::inventory::{MaterialLotId, StockpileStorageError};
use crate::maintenance::{ActiveConditionDurationError, Condition};
use crate::material::MaterialId;

mod display;
mod source;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlayerWorkValidationError {
    WorkWithoutPlayer,
    RevisionExhausted,
    SurvivalRevisionExhausted,
    ManualProductionJobMissing,
    ManualProductionProcessMismatch,
    ManualProductionScheduleInvalid,
    MiningJobMissing,
    MiningJobNotWorking,
    MiningMethodMissing,
    MiningScheduleInvalid,
    ManualProductionMissingWork,
    MultiplePlayerJobs,
    MiningMissingWork,
    ManualPowerMethodMissing,
    ManualPowerEquipmentMissing,
    ManualPowerEquipmentDefinitionMismatch,
    ManualPowerEquipmentConditionMismatch,
    ManualPowerEquipmentRequiresStructuralSupport,
    ManualPowerEquipmentMounted,
    ManualPowerDestinationMissing,
    ManualPowerDestinationDefinitionMismatch,
    ManualPowerCarrierMismatch,
    ManualPowerDestinationCannotAcceptEnergy,
    ManualPowerDestinationCapacityExceeded,
    ManualPowerEquipmentCapabilityMissing,
    ManualPowerEquipmentCapabilityKindMismatch,
    ManualPowerZeroPower,
    ManualPowerScheduleInvalid,
    ManualPowerDurationMismatch,
    ManualPowerConditionDuration(ActiveConditionDurationError),
    ManualPowerConditionMismatch,
    ManualPowerResourceDoubleBooked,
    ManualPowerEquipmentRevisionExhausted,
    ManualPowerEnergyRevisionExhausted,
    ProspectingMethodMissing,
    ProspectingUnknownMaterial {
        material: MaterialId,
    },
    ProspectingRegionVolumeOverflow,
    ProspectingRegionTooLarge {
        actual: u128,
        maximum: u128,
    },
    ProspectingEquipmentMissing,
    ProspectingUnexpectedEquipment {
        equipment: EquipmentId,
    },
    ProspectingEquipmentDefinitionMismatch,
    ProspectingEquipmentDefinitionNotAccepted {
        equipment: EquipmentId,
    },
    ProspectingEquipmentConditionMismatch,
    ProspectingEquipmentMounted {
        equipment: EquipmentId,
    },
    ProspectingEquipmentConditionDuration(ActiveConditionDurationError),
    ProspectingEquipmentConditionOutcomeMismatch {
        stored: Condition,
        required: Condition,
    },
    ProspectingEquipmentResourceDoubleBooked {
        equipment: EquipmentId,
    },
    ProspectingObservationIdExhausted,
    ProspectingKnowledgeRevisionExhausted,
    ProspectingEquipmentRevisionExhausted,
    ProspectingScheduleInvalid,
    ProspectingDurationMismatch,
    EatingMassInvalid {
        mass: Mass,
    },
    EatingScheduleInvalid,
    EatingDurationMismatch,
    DrinkingVolumeInvalid {
        volume: Volume,
    },
    DrinkingScheduleInvalid,
    DrinkingDurationMismatch,
    EquipmentMaintenanceEquipmentMissing,
    EquipmentMaintenanceDefinitionMismatch,
    EquipmentMaintenanceConditionMismatch,
    EquipmentMaintenanceProfileMissing,
    EquipmentMaintenanceTargetMismatch,
    EquipmentMaintenanceScheduleInvalid,
    EquipmentMaintenanceDurationMismatch,
    EquipmentMaintenanceResourceDoubleBooked,
    EquipmentMaintenanceEquipmentRevisionExhausted,
    StorageDismantlingTargetMissing,
    StorageDismantlingEnclosureMissing,
    StorageDismantlingDefinitionMissing,
    StorageDismantlingDefinitionMismatch,
    StorageDismantlingEnclosureIdentityMismatch,
    StorageDismantlingRecoveredMassMismatch,
    StorageDismantlingTargetMounted,
    StorageDismantlingTargetReservedInbound,
    StorageDismantlingRecoveryMissing,
    StorageDismantlingRecoveryIsTarget,
    StorageDismantlingRecoveryMounted,
    StorageDismantlingRecoveryStorage(StockpileStorageError),
    StorageDismantlingStorageProfileMismatch,
    StorageDismantlingTargetContentsIncompatible {
        lot: MaterialLotId,
    },
    StorageDismantlingRecoveryLotIdExhausted,
    StorageDismantlingScheduleInvalid,
    StorageDismantlingDurationMismatch,
    StorageDismantlingResourceDoubleBooked,
    StorageDismantlingInventoryRevisionExhausted,
    PendingDirectConsumptionWithoutWork,
    EatingConsumptionMissing,
    EatingConsumptionMismatch,
    DrinkingConsumptionMissing,
    DrinkingConsumptionMismatch,
    PlayerDead,
    MetabolicCostOverflow,
    InsufficientMetabolicEnergy {
        available: Energy,
        required: Energy,
    },
    HydrationCostOverflow,
    InsufficientHydration {
        available: Volume,
        required: Volume,
    },
}
